# Eight powerfull tools in data analysis
1. groupby()
2. pivot_table()
3. Aggregate()
4. cross_tab()
5. concat()
6. apply()
7. lambda()
8. del(keyword)

### 1. Groupby ()
* Discrite/catogorical - It is measurable and countable and does'nt have units.
* Continueous  - It will have units.
* When you need to group two column , then you need to use one continueous followd by, means ["region","sex"]["charges"] - Two discrite / one contineous.

In [1]:
import pandas as pd

In [28]:
Insurance_data = pd.read_csv("Insurance.csv")
Insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

#### Give the average charges from the each region.

In [11]:
Insurance_data.groupby("region")["charges"].mean().round(2).sort_values()

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

#### Give the average charges from the each region and sex.

In [17]:
Insurance_data.groupby(["region","sex"])["charges"].mean().round(2).sort_values(ascending = False)

region     sex
southeast  male      15879.62
northeast  male      13854.01
southeast  female    13499.67
southwest  male      13412.88
northeast  female    12953.20
northwest  female    12479.87
           male      12354.12
southwest  female    11274.41
Name: charges, dtype: float64

### 2. pivot_table ()
* It will make the data's in more presentable in table.

In [25]:
pd.pivot_table(data = Insurance_data,values="charges",index="region",columns=["sex","smoker"]).round(2)

sex         female               male
smoker          no       yes       no       yes
region
northeast  9640.43  28032.05  8664.04  30926.25
northwest  8787.00  29670.82  8320.69  30713.18
southeast  8440.21  33034.82  7609.00  36029.84
southwest  8234.09  31687.99  7778.91  32598.86

### 3. Aggregate ()
* sum()
* min()
* max()
* mean()
#### 3.1 Suppose, I need to find the average,min,max,sum of charges with respect to region

In [34]:
Insurance_data.groupby(["region","sex"])["charges"].agg(["mean","min","max","sum"]).round(2)

                      mean      min       max         sum
region    sex
northeast female  12953.20  2196.47  58571.07  2085465.71
          male    13854.01  1694.80  48549.18  2258202.88
northwest female  12479.87  2117.34  55135.40  2046698.75
          male    12354.12  1621.34  60021.40  1989013.25
southeast female  13499.67  1607.51  63770.43  2362442.12
          male    15879.62  1121.87  62592.87  3001247.65
southwest female  11274.41  1727.78  48824.45  1826454.62
          male    13412.88  1241.56  52590.83  2186300.02

### 4. Cross_tab ()
* To compute the frequence of two or more catogorical features

#### 4.1 How many smoker and non - smoker are there based on region

In [39]:
pd.crosstab(Insurance_data["region"], Insurance_data["smoker" ],margins = True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

### 5. concat ()

* It use to combine the different dataset into one dataset by appending one after another.
* we need to use this function when the different dataset will haves the same column or obervations name.

In [42]:
sales_17 = pd.read_csv("Sales-transaction-2017.csv")
sales_18 = pd.read_csv("Sales-transaction-2018.csv")
sales_19 = pd.read_csv("Sales-transaction-2019.csv")

In [81]:
# I need to concat this three datasets.

sales_combined = pd.concat([sales_17,sales_18,sales_19])
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [82]:
sales_combined.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

#### Step 1 - Remove Duplicate

In [83]:
sales_combined.drop_duplicates(inplace = True)
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### Step 2 - Fill missing values with mean()

In [84]:
sales_combined.drop(columns = ["Gross","Disc","Voucher Amount"])

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40"

In [48]:
# Target

Target = pd.read_csv("Sales-transaction-edited.csv")
Target

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [49]:
Target.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

### 6. Apply ()

#### Create a new column with the name of "Eligible criteria" in that if age > 20 return eligible else not eligible

In [87]:
def age_criteria(x):
    if x > 20:
        return "Eligible"
    else:
        return "Not Eligible"

In [95]:
Insurance_data["Eligible Criteria"] = Insurance_data["age"].apply(age_criteria)
Insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria,Eligible Criteria2
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,0
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,0
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,1
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,1
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,1
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,1
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,0
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,0
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,1
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,1

### 7. lambda ()

Create a new column with the name of "Eligible criteria" in that if age > 20 return eligible else not eligible by using lambda in simple.

In [104]:
Insurance_data["Eligible Criteria2"] = Insurance_data["age"].apply(lambda x: 1 if x>20 else 0)
Insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria,Eligible Criteria2
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,0
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,0
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,1
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,1
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,1
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,1
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,0
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,0
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,1
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,1

### 8. Delete () - del

In [105]:
# It will delete one column at a time 

del Insurance_data["Eligible Criteria2"]

In [106]:
Insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible