## Task 1 - Data Cleaning Challenge on Sales Data.

In [125]:
import pandas as pd

In [126]:
# combining three datasets using concat()

sales_17 = pd.read_csv("Sales-transaction-2017.csv")
sales_18 = pd.read_csv("Sales-transaction-2018.csv")
sales_19 = pd.read_csv("Sales-transaction-2019.csv")

In [127]:
sales_combined = pd.concat([sales_17,sales_18,sales_19])
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### Step 1 - Remove duplicate data

In [128]:
sales_combined.drop_duplicates(inplace = True)
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### Step 2 - Checking missing values and replacing NaN with 0

In [129]:
sales_combined.isna().sum()

Date                204
Voucher             170
Party                35
Product             204
Qty                 170
Rate                171
Gross               171
Disc              92951
Voucher Amount    70984
dtype: int64

In [130]:
sales_combined["Voucher Amount"] = sales_combined["Voucher Amount"].fillna(0)
sales_combined["Disc"]           = sales_combined["Disc"].fillna(0)

In [131]:
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",0,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",0,0
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",0,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",0,0
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",0,0
...,...,...,...,...,...,...,...,...,...
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",0,0
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",0,0
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",0,0
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### Step 3 - Remove all rows where any of these columns contain missing values (NaN).

In [132]:
sales_combined.dropna(subset=["Date", "Voucher", "Party", "Product", "Qty", "Rate", "Gross"],inplace = True)

In [133]:
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",0,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",0,0
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",0,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",0,0
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",0,0
...,...,...,...,...,...,...,...,...,...
19167,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",0,0
19168,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",0,0
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",0,0
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",0,0
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",0,0

In [134]:
sales_combined.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [135]:
sales_combined["Date"] = pd.to_datetime(sales_combined["Date"],errors="coerce")

In [136]:
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",0,"13,100.00"
1,2017-01-04,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",0,0
2,2017-01-04,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",0,"30,990.00"
3,2017-01-04,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",0,0
4,2017-01-04,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",0,0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",0,0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",0,0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",0,0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",0,0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",0,0

In [137]:
sales_combined["Rate"] = pd.to_numeric(sales_combined["Rate"].str.replace(",", ""),errors="coerce")

sales_combined["Gross"] = pd.to_numeric(sales_combined["Gross"].str.replace(",", ""),errors="coerce")

sales_combined["Disc"] = pd.to_numeric(sales_combined["Disc"].str.replace(",", ""),errors="coerce")

sales_combined["Voucher Amount"] = pd.to_numeric(sales_combined["Voucher Amount"].str.replace(",", ""),errors="coerce")

In [138]:
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,NaN,13100.0
1,2017-01-04,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,NaN,NaN
2,2017-01-04,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,NaN,30990.0
3,2017-01-04,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,NaN,NaN
4,2017-01-04,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,NaN,NaN
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,NaN,NaN
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,NaN,NaN
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,NaN,NaN
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,NaN,NaN

In [139]:
sales_combined["Voucher Amount"] = sales_combined["Voucher Amount"].fillna(0)
sales_combined["Disc"]           = sales_combined["Disc"].fillna(0)

In [140]:
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,13100.0
1,2017-01-04,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,0.0
2,2017-01-04,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,30990.0
3,2017-01-04,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,0.0
4,2017-01-04,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,0.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,0.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,0.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,0.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,0.0

In [141]:
sales_combined["Qty"] = pd.to_numeric(sales_combined["Qty"],errors="coerce")

In [142]:
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,0.0,13100.0
1,2017-01-04,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,0.0
2,2017-01-04,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,0.0,30990.0
3,2017-01-04,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,0.0
4,2017-01-04,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,0.0,0.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,0.0,0.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,0.0,0.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,0.0,0.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,0.0,0.0

In [143]:
sales_combined["Voucher"] = sales_combined["Voucher"].str.replace("Sal:", "", regex=False)

In [144]:
sales_combined["Voucher"] = pd.to_numeric(sales_combined["Voucher"],errors="coerce")

In [145]:
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,1.0,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,0.0,13100.0
1,2017-01-04,1.0,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,0.0
2,2017-01-04,2.0,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,0.0,30990.0
3,2017-01-04,2.0,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,0.0
4,2017-01-04,2.0,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,4935.0,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,0.0,0.0
19168,2019-10-10,4935.0,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,0.0,0.0
19169,2019-10-10,4935.0,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,0.0,0.0
19170,2019-10-10,4935.0,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,0.0,0.0
19171,2019-10-10,4935.0,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,0.0,0.0

In [146]:
sales_combined.dtypes

Date              datetime64[ns]
Voucher                  float64
Party                     object
Product                   object
Qty                      float64
Rate                     float64
Gross                    float64
Disc                     float64
Voucher Amount           float64
dtype: object

In [147]:
sales_combined["Date"] = pd.to_datetime(sales_combined["Date"],dayfirst=True,errors="coerce")

In [148]:
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,1.0,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,0.0,13100.0
1,2017-01-04,1.0,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,0.0
2,2017-01-04,2.0,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,0.0,30990.0
3,2017-01-04,2.0,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,0.0
4,2017-01-04,2.0,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,4935.0,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,0.0,0.0
19168,2019-10-10,4935.0,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,0.0,0.0
19169,2019-10-10,4935.0,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,0.0,0.0
19170,2019-10-10,4935.0,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,0.0,0.0
19171,2019-10-10,4935.0,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,0.0,0.0

In [149]:
sales_combined.dropna(subset=["Date", "Voucher", "Qty", "Rate", "Gross"],inplace = True)

In [150]:
sales_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,1.0,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,0.0,13100.0
1,2017-01-04,1.0,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,0.0
2,2017-01-04,2.0,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,0.0,30990.0
3,2017-01-04,2.0,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,0.0
4,2017-01-04,2.0,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,4935.0,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,0.0,0.0
19168,2019-10-10,4935.0,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,0.0,0.0
19169,2019-10-10,4935.0,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,0.0,0.0
19170,2019-10-10,4935.0,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,0.0,0.0
19171,2019-10-10,4935.0,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,0.0,0.0

In [151]:
sales_combined.isna().sum()

Date              0
Voucher           0
Party             0
Product           0
Qty               0
Rate              0
Gross             0
Disc              0
Voucher Amount    0
dtype: int64

In [152]:
sales_combined.dtypes

Date              datetime64[ns]
Voucher                  float64
Party                     object
Product                   object
Qty                      float64
Rate                     float64
Gross                    float64
Disc                     float64
Voucher Amount           float64
dtype: object

## Task 2 - Merge Function 1 Example
1. inner merge
2. outer merge
3. left merge
4. right merge
5. cross merge

In [156]:
sales_17 = pd.read_csv("Sales-transaction-2017.csv")
insurance_details = pd.read_csv("Insurance.csv")

In [157]:
sales_17.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN

In [159]:
sales_18.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN

In [164]:
sales17_summary = sales_17.groupby("Product")["Qty"].sum().reset_index()

sales18_summary = sales_18.groupby("Product")["Qty"].sum().reset_index()

# Inner Merge
inner_merge = pd.merge(sales17_summary, sales18_summary,on="Product", how="inner",suffixes=("_2017", "_2018"))

# Left Merge
left_merge = pd.merge(sales17_summary, sales18_summary,on="Product", how="left",suffixes=("_2017", "_2018"))

# Right Merge
right_merge = pd.merge(sales17_summary, sales18_summary,on="Product", how="right",suffixes=("_2017", "_2018"))

# Outer Merge
outer_merge = pd.merge(sales17_summary, sales18_summary,on="Product", how="outer",suffixes=("_2017", "_2018"))

In [167]:
inner_merge.head()

,Product,Qty_2017,Qty_2018
0,,...,...
1,"10"" CLASSIFOAM-1200",11111221222112212,2211
2,10*10 NILKAMAL,2525515252525252525252525252552552515555502550...,550550502515052550501503015025
3,10*10 ROYAL,55405,351010303010302010171057020
4,10*10 Radha Krishna,2525525252525252525255252525252525252552552550...,5052525125255021025102550225552550225502255502...

In [168]:
outer_merge.head()

,Product,Qty_2017,Qty_2018
0,,...,...
1,"10"" CLASSIFOAM-1200",11111221222112212,2211
2,"10"" Essfoam Loose",10300,NaN
3,"10"" SILVER HEAVY",NaN,10
4,"10"" THERMOCOL PRINT",NaN,500150

In [169]:
right_merge.head()

,Product,Qty_2017,Qty_2018
0,,...,...
1,"10"" CLASSIFOAM-1200",11111221222112212,2211
2,"10"" SILVER HEAVY",NaN,10
3,"10"" THERMOCOL PRINT",NaN,500150
4,10*10 DHAVAT,NaN,25252525202525

In [170]:
left_merge.head()

,Product,Qty_2017,Qty_2018
0,,...,...
1,"10"" CLASSIFOAM-1200",11111221222112212,2211
2,"10"" Essfoam Loose",10300,NaN
3,10*10 MORE,2510252532525251025152525552525252510252510525...,NaN
4,10*10 NILKAMAL,2525515252525252525252525252552552515555502550...,550550502515052550501503015025

In [171]:
# Cross merge

cross_merge = pd.merge(sales17_summary.head(10),sales18_summary.head(10),how="cross",suffixes=("_2017", "_2018"))
cross_merge.head()

,Product_2017,Qty_2017,Product_2018,Qty_2018
0,,...,,...
1,,...,"10"" CLASSIFOAM-1200",2211
2,,...,"10"" SILVER HEAVY",10
3,,...,"10"" THERMOCOL PRINT",500150
4,,...,10*10 DHAVAT,25252525202525

In [172]:
# Merge with indicator

indicator_merge = pd.merge(sales17_summary,sales18_summary,on="Product",how="outer",indicator=True,suffixes=("_2017", "_2018"))
indicator_merge.head()

,Product,Qty_2017,Qty_2018,_merge
0,,...,...,both
1,"10"" CLASSIFOAM-1200",11111221222112212,2211,both
2,"10"" Essfoam Loose",10300,NaN,left_only
3,"10"" SILVER HEAVY",NaN,10,right_only
4,"10"" THERMOCOL PRINT",NaN,500150,right_only

## Task 3 - List Comprehension 2 examples

#### Example 1 - Find Passed Students

In [6]:
student_marks = [30,40,60,90,26,39,70,100]

passed_studend = [i for i in student_marks if i >= 40]

print("Passed students:",passed_studend)

Passed students: [40, 60, 90, 70, 100]

#### Example 2 - Find employees assigned to active projects.

In [29]:
import pandas as pd

In [30]:
employees                  = ["Dhanush","Ram","Kumar","Sundar","Virat"]
projects                   = ["AI Project", "Web App", "Testing","Model bulding","Data cleaning"]
Inactive_employees         = ["Kumar","Ram"]

project_assigned_employees = [[emp,"No project" if emp in Inactive_employees else proj,"InActive" if emp in Inactive_employees else "Active"] 
                              for [emp,proj] in zip(employees,projects)]

pd.DataFrame(data = project_assigned_employees)

         0              1         2
0  Dhanush     AI Project    Active
1      Ram     No project  InActive
2    Kumar     No project  InActive
3   Sundar  Model bulding    Active
4    Virat  Data cleaning    Active

## Task 4 - Lambda Function 2 examples with Map, Filter, Reduce

#### 1. MAP – Increase charges by 10%

In [33]:
insurance_data_charges = pd.read_csv("Insurance.csv")
insurance_data_charges

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [34]:
insurance_data_charges["charges"] = list(map(lambda charge: charge * 1.10,insurance_data_charges["charges"]))
insurance_data_charges

      age     sex     bmi  children smoker     region       charges
0      19  female  27.900         0    yes  southwest  18573.416400
1      18    male  33.770         1     no  southeast   1898.107530
2      28    male  33.000         3     no  southeast   4894.408200
3      33    male  22.705         0     no  northwest  24182.917671
4      32    male  28.880         0     no  northwest   4253.540720
...   ...     ...     ...       ...    ...        ...           ...
1333   50    male  30.970         3     no  northwest  11660.603130
1334   18  female  31.920         0     no  northeast   2426.578880
1335   18  female  36.850         0     no  southeast   1792.816850
1336   21  female  25.800         0     no  southwest   2208.739500
1337   61  female  29.070         0    yes  northwest  32055.496330

[1338 rows x 7 columns]

#### 2. FILTER - Find customers whose insurance charges are greater than ₹15,000.

In [40]:
insurance_data_charges["charges"] = list(map(lambda charge: charge > 15000,insurance_data_charges["charges"]))
insurance_data_charges

      age     sex     bmi  children smoker     region  charges
0      19  female  27.900         0    yes  southwest     True
1      18    male  33.770         1     no  southeast    False
2      28    male  33.000         3     no  southeast    False
3      33    male  22.705         0     no  northwest     True
4      32    male  28.880         0     no  northwest    False
...   ...     ...     ...       ...    ...        ...      ...
1333   50    male  30.970         3     no  northwest    False
1334   18  female  31.920         0     no  northeast    False
1335   18  female  36.850         0     no  southeast    False
1336   21  female  25.800         0     no  southwest    False
1337   61  female  29.070         0    yes  northwest     True

[1338 rows x 7 columns]

#### 3. REDUCE – Find the Highest goal scored by a team.

In [42]:
from functools import reduce

In [54]:
euro_football = pd.read_csv("Euro_2012.csv")
euro_football.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [66]:
highest_goal_team = reduce(lambda x, y: x if x["Goals"] > y["Goals"] else y,euro_football.to_dict("records"))

pd.DataFrame(
    {
        "Team": [highest_goal_team["Team"]],
        "Goals": [highest_goal_team["Goals"]]
    }
)

    Team  Goals
0  Spain     12