# Task 1 - Conceptual Questions

#### 1. Why is Python preferred in the field of Data Science?

* Python is widely preferred in Data Science because it is simple to learn, easy to read, and supports a large number of libraries for data analysis, visualization, machine learning, and artificial intelligence.
* It allows data scientists to perform complex tasks with less code compared to many other programming languages.
* Its ability to integrate with databases, web applications, and machine learning frameworks makes it one of the most popular choices in the Data Science industry.

#### 2. What is the difference between a Jupyter Notebook and Google Colab?

* Jupyter Notebook and Google Colab are interactive environments used for writing and executing Python code.
* The main difference is that Jupyter Notebook runs on a user's local machine and requires installation.
* whereas Google Colab runs on Google's cloud servers and can be accessed through a web browser without installation.
* But in Google Colab some key functions are missing.
* So I'll recommand Jupyter Notebook to use.

#### 3. When would you use a list over a set or a tuple?

* list used when the conditions allows to store duplicate values, Support adding, removing, or modifying elements and allow different datatypes inside one variable.
* Set used when the conditions doesn't allows duplicate values, It is mutable using build - in function and allow different datatypes inside one variable.
* A tuple is used when the data should remain unchanged after creation.

#### 4. What is exception handling? Give a real-life example of when it's useful.

* Exception handling is a programming technique used to detect and manage errors that occur during program execution.
* Instead of allowing a program to crash when an error occurs, exception handling enables the program to respond gracefully and continue running.

In [7]:
# Example

try:
    user_input_1 = int(input("Enter your number:"))
    user_input_2 = int(input("Enter your second number:"))
    
    division = user_input_1/user_input_2
    print(division)
    
except ZeroDivisionError:
    print("You input is invalid, {} can't able to divide {}. so try to use more than zero".format(user_input_2,user_input_1))

except ValueError:                              
    print("You input is invalid, Try to use numbers as input.")                               

finally:
    print("Program Ended!!")

Enter your number: r

You input is invalid, Try to use numbers as input.
Program Ended!!

#### 5. Define DataFrame and Series in Pandas. What's the difference?

* DataFrame and Series both are from the pandas libraries.
* DataFrame is used to represent the data in table in 2D data structure.
* Series is used to represent the data in 1D data structure.
* The main difference is that a Series contains only one column of data.
* whereas a DataFrame can contain multiple columns with different data types

#### 6. What are the different ways of dealing with missing values in a dataset?

* To deal with missing values, I will use build-in fuctions to solve it.
* I use dropna() function to drop the missing values in dataset.
* Or I use Column mean to fill the missing value. But it is not recommended.

#### 7. How do NumPy and Pandas differ in terms of functionality?
* NumPy and Pandas are both important Python libraries used in Data Science.
* NumPy is mainly designed for numerical computations and efficient handling of multidimensional arrays.
* Pandas is mainly designed for Data visualization.
* It provides data structures such as Series and DataFrame, which make it easier to work with structured and tabular data.

#### 8. What is the role of libraries like Seaborn and Matplotlib in a data project?

* Both seaborn and matplotlib are data visualization libraries. That will represent the data's in graphically.
* Matplotlib will represent the data using basic graphs like bar plot, scatter plot, line plot etc..
* Seaborn is built on top of Matplotlib and offers more attractive and informative statistical visualizations than matplotlib.
* These libraries help identify trends, patterns, relationships, and outliers within data, making them essential tools in data analysis and reporting.

#### 9. When should you use .loc[] and when .iloc[]?
* Both are use to access the rows and column in pandas

In [2]:
import pandas as pd
employee_details = pd.read_csv("emp_data.csv").head()
employee_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

In [3]:
# .loc[] - It will uses observations and parameters names

employee_details.loc[0,"Name"]

'Rajesh'

In [5]:
# .iloc[] - It will uses position values to access the perticular values from the dataset

employee_details.iloc[0,1]

29.0

#### 10. What is the importance of writing functions in Python?

* Functions are reusable block of code.
* It will helps us to minimize the code structure.
* It will organize the code in structure.
* Onces the function is created, We can able to use that function at any lines in future.
* There are user-define function and pre-define function are there.
* The user-define function are created by us manually.
* The pre-define function are already created by someone and imported in python.Example(len(),max(),min(),append()...etc)

# Task 2 - Scripting-Based Questions

## 1. Write a program to take a name and age from the user and print a greeting message.

In [1]:
user_name = input("Enter your name:")
user_age  = int(input("Enter your age:"))

print("Welcome to this course {}, and Please confrim your age:{}".format(user_name,user_age))

Enter your name: Dhanush
Enter your age: 22

Welcome to this course Dhanush, and Please confrim your age:22

## 2. Create a list of numbers and print only even numbers using a for loop.

In [4]:
list_of_numbers = range(1,51)
even_numbers    = []

for i in (list_of_numbers):
    if i % 2 == 0:
        even_numbers.append(i)
print(even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]

## 3. Write a program that handles division by zero using try-except.

In [22]:
try:
    user_input_1 = int(input("Enter your number:"))
    user_input_2 = int(input("Enter your second number:"))
    
    division = user_input_1/user_input_2
    print(division)
    
except ZeroDivisionError:
    print("You input is invalid, {} can't able to divide {}. so try to use more than zero".format(user_input_2,user_input_1))

except ValueError:                              
    print("You input is invalid, Try to use numbers as input.")                               

finally:
    print("Program Ended!!")

Enter your number: r

You input is invalid, Try to use numbers as input.
Program Ended!!

## 4. Given a string, count how many vowels it has.

In [29]:
user_input  = input("Enter the string:").lower()
vowels      = "aeiou"
vowels_list = []

for i in user_input:
    if i in vowels:
        vowels_list.append(i)
print("Number of vowles:",vowels_list)
print("Count of vowles:",len(vowels_list))

Enter the string: dhanush

Number of vowles: ['a', 'u']
Count of vowles: 2

## 5. Reverse a list without using built-in functions.

In [30]:
list_of_items = ["apple","orange","22","vellore","93.9"]

reverse       = list_of_items[::-1]
print(reverse)

['93.9', 'vellore', '22', 'orange', 'apple']

## 6. Create a dictionary with at least 5 key-value pairs and print them.

In [44]:
import pandas as pd

In [46]:
exam_marks = {"Name"   : ["Raju","Jaggu","Bheem","Kaliya","Dolu","Bolu"],
              "Maths"  : [63,72,96,63,95,99],
             "Science" : [99,72,52,99,99,100],
              "Social" : [61,73,92,100,98,96],
              "Tamil"  : [62,74,93,77,97,97],
              "English": [63,75,94,66,96,94],
              "P.E"    : [64,76,95,63,95,93]
             }

exam_marks

{'Name': ['Raju', 'Jaggu', 'Bheem', 'Kaliya', 'Dolu', 'Bolu'],
 'Maths': [63, 72, 96, 63, 95, 99],
 'Science': [99, 72, 52, 99, 99, 100],
 'Social': [61, 73, 92, 100, 98, 96],
 'Tamil': [62, 74, 93, 77, 97, 97],
 'English': [63, 75, 94, 66, 96, 94],
 'P.E': [64, 76, 95, 63, 95, 93]}

In [47]:
pd.DataFrame(data = exam_marks)

     Name  Maths  Science  Social  Tamil  English  P.E
0    Raju     63       99      61     62       63   64
1   Jaggu     72       72      73     74       75   76
2   Bheem     96       52      92     93       94   95
3  Kaliya     63       99     100     77       66   63
4    Dolu     95       99      98     97       96   95
5    Bolu     99      100      96     97       94   93

## 7. Write a Pandas code to read a CSV and print the top 5 rows.

In [48]:
Football = pd.read_csv(filepath_or_buffer = "Euro_2012.csv").head()
Football

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

## 8. Create a DataFrame from a Python dictionary.

In [49]:
exam_marks = {"Name"   : ["Raju","Jaggu","Bheem","Kaliya","Dolu","Bolu"],
              "Maths"  : [63,72,96,63,95,99],
             "Science" : [99,72,52,99,99,100],
              "Social" : [61,73,92,100,98,96],
              "Tamil"  : [62,74,93,77,97,97],
              "English": [63,75,94,66,96,94],
              "P.E"    : [64,76,95,63,95,93]
             }

exam_marks

pd.DataFrame(data = exam_marks)

     Name  Maths  Science  Social  Tamil  English  P.E
0    Raju     63       99      61     62       63   64
1   Jaggu     72       72      73     74       75   76
2   Bheem     96       52      92     93       94   95
3  Kaliya     63       99     100     77       66   63
4    Dolu     95       99      98     97       96   95
5    Bolu     99      100      96     97       94   93

## 9. Replace all missing values in a DataFrame with the column’s mean.

In [51]:
employee_details = pd.read_csv(filepath_or_buffer = "emp_data.csv")
employee_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [55]:
employee_details.drop_duplicates(inplace = True)
employee_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

In [59]:
employee_details["Salary"].fillna(value = employee_details["Salary"].mean(),inplace = True)

C:\Users\V.DHANUSH\AppData\Local\Temp\ipykernel_10916\3577666570.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employee_details["Salary"].fillna(value = employee_details["Salary"].mean(),inplace = True)

In [60]:
employee_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

## 10. Filter rows in a DataFrame where the "Age" column is greater than 30.

In [65]:
employee_details[employee_details["Age"]>30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech  62500.0  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022