# Task_1. Function Example For all Python Data Structure

#### Four Data Structures
* List
* Sets
* Tuple
* Dictionary - key:value pairs

## 1) List - []

In [5]:
# remove() items from the list

item_to_buy_1 = ["apple","orange","graphs","watermelon","Jack Fruit"]
item_to_buy_1.remove("apple")

item_to_buy_1

['orange', 'graphs', 'watermelon', 'Jack Fruit']

In [6]:
# append() items to the list

item_to_buy_2 = ["apple","orange","graphs","watermelon","Jack Fruit"]
item_to_buy_2.append("banana")

item_to_buy_2

['apple', 'orange', 'graphs', 'watermelon', 'Jack Fruit', 'banana']

In [9]:
# count() number of items in the list

item_to_buy_3 = ["apple","orange","graphs","watermelon","Jack Fruit","apple"]
print(item_to_buy_3.count("apple"))

2

In [13]:
# sort() the list of items

item_to_buy_4 = ["apple","orange","graphs","watermelon","jackFruit","apple"]
item_to_buy_4.sort()
print(item_to_buy_4)

['apple', 'apple', 'graphs', 'jackFruit', 'orange', 'watermelon']

In [17]:
# reverse() the list of items

item_to_buy_5 = ["apple","orange","graphs","watermelon","jackFruit"]
item_to_buy_5.reverse()
print(item_to_buy_5)

['jackFruit', 'watermelon', 'graphs', 'orange', 'apple']

In [20]:
# Using pop() function to remove the perticular values using it's index value.

item_to_buy_6 = ["apple","orange","graphs","watermelon","jackFruit"]
item_to_buy_6.pop(2)
print(item_to_buy_6)

['apple', 'orange', 'watermelon', 'jackFruit']

In [24]:
# Using insert() function to insert the value using the before index value from the list

item_to_buy_7 = ["apple","orange","graphs","watermelon","jackFruit"]
item_to_buy_7.insert(2,"Banana")
print(item_to_buy_7)

['apple', 'orange', 'Banana', 'graphs', 'watermelon', 'jackFruit']

In [26]:
# Using index() function to return the index value of the perticular item from the list.

item_to_buy_8 = ["apple","orange","graphs","watermelon","jackFruit"]
print(item_to_buy_8.index("watermelon"))

3

In [27]:
# Using extend() function to extend the list of items

item_to_buy_9 = ["apple","orange","graphs","watermelon","jackFruit"]
item_to_buy_9.extend(["pine apple","dragon fruit"])
print(item_to_buy_9)

['apple', 'orange', 'graphs', 'watermelon', 'jackFruit', 'pine apple', 'dragon fruit']

In [29]:
# Using copy() function for making the copy list of original list

item_to_buy_10 = ["apple","orange","graphs","watermelon","jackFruit"]
copy_of_list = item_to_buy_10.copy()
print(copy_of_list)

['apple', 'orange', 'graphs', 'watermelon', 'jackFruit']

In [31]:
# Using clear() function to turminate the list of items

item_to_buy_11 = ["apple","orange","graphs","watermelon","jackFruit"]
item_to_buy_11.clear()
print(item_to_buy_11)

[]

## Sets - {}

In [33]:
# Using add() to add values to the sets

client_name_1 = {"dhanush","ram","bheem","jaggu"}
client_name_1.add("motu")
print(client_name_1)

{'motu', 'bheem', 'ram', 'jaggu', 'dhanush'}

In [36]:
# Using update() to update values to the sets

client_name_2 = {"dhanush","ram","bheem","jaggu"}
client_name_2.update({"dolu","bolu"})
print(client_name_2)

{'dolu', 'bheem', 'ram', 'bolu', 'jaggu', 'dhanush'}

In [37]:
# Using remove()

client_name_3 = {"dhanush","ram","bheem","jaggu"}
client_name_3.remove("bheem")
print(client_name_3)

{'jaggu', 'dhanush', 'ram'}

In [41]:
# Using pop()

client_name_4 = {"dhanush","ram","bheem","jaggu"}
client_name_4.pop()
print(client_name_4)

{'dhanush', 'bheem', 'ram'}

In [42]:
# Using copy()

client_name_5   = {"dhanush","ram","bheem","jaggu"}
new_client_list = client_name_5.copy()
print(new_client_list)

{'jaggu', 'dhanush', 'bheem', 'ram'}

In [44]:
# Using clear()

client_name_6 = {"dhanush","ram","bheem","jaggu"}
client_name_6.clear()
print(client_name_6)

set()

In [45]:
# Using union()

client_name_7 = {"dhanush","ram","bheem","jaggu"}
new_client    = {"dolu","bolu"}
updated_list  = client_name_7.union(new_client)
print(updated_list)

{'dolu', 'bheem', 'ram', 'bolu', 'jaggu', 'dhanush'}

In [49]:
# Using difference()

client_name_8 = {"dhanush","ram","bheem","jaggu"}
new_client    = {"ram","jaggu"}
updated_list  = client_name_8.difference(new_client)
print(updated_list)

{'dhanush', 'bheem'}

In [55]:
# Using difference_update()

client_name_9 = {"dhanush","ram","bheem","jaggu"}
new_client    = {"ram","jaggu"}
client_name_9.difference_update(new_client)
print(client_name_9)

{'bheem', 'dhanush'}

In [56]:
# Using intersection_update()

client_name_10 = {"dhanush","ram","bheem","jaggu"}
new_client    = {"ram","jaggu"}
client_name_10.intersection_update(new_client)
print(client_name_10)

{'jaggu', 'ram'}

In [58]:
# Using intersection()

client_name_11 = {"dhanush","ram","bheem","jaggu"}
new_client    = {"ram","jaggu"}
updated_list  = client_name_11.intersection(new_client)
print(updated_list)

{'jaggu', 'ram'}

In [61]:
# Using discard()

client_name_12 = {"dhanush","ram","bheem","jaggu"}
client_name_12.discard("ram")
print(client_name_12)

{'jaggu', 'dhanush', 'bheem'}

In [65]:
# Using isdisjoint() - checking any common values between two variables

client_name_12 = {"dhanush","ram","bheem","jaggu"}
new_client     = {"vijay","rajini"}
print(client_name_12.isdisjoint(new_client))

True

In [68]:
# Using issubset() - checks whether all values from set1 are equals the set2

client_name_12 = {"dhanush","ram","bheem","jaggu"}
new_client     = {"vijay","rajini"}
print(client_name_12.issubset(new_client))

False

In [72]:
# Using issuperset()

client_name_12 = {"dhanush","ram","bheem","jaggu"}
new_client     = {"dhanush","bheem"}
print(client_name_12.issuperset(new_client))

True

In [74]:
# Using symmetric_difference()

client_name_12 = {"dhanush","ram","bheem","jaggu"}
new_client     = {"dhanush","bheem"}
print(client_name_12.symmetric_difference(new_client))

{'jaggu', 'ram'}

In [77]:
# Using symmetric_difference()

client_name_13 = {"dhanush","ram","bheem","jaggu"}
new_client     = {"dhanush","bheem"}
client_name_13.symmetric_difference_update(new_client)
print(client_name_13)

{'jaggu', 'ram'}

## Tuple ()

In [81]:
# Using count() - To find number of duplicate values in tuple.

store_product = ("iphone18","airpods","laptop","mouse","laptop")
print(store_product.count("laptop"))

2

In [84]:
# Using index() - To find exact location using index value
 
store_product = ("iphone18","airpods","laptop","mouse","laptop")
print(store_product.index("mouse"))

3

## Dictionary {}

In [85]:
# Store customer details

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details

{'Name': 'Dhanush',
 'Age': 22,
 'product_purchased': 'Laptop',
 'Amount_paid': 72000}

In [86]:
# Using keys() 

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.keys()

dict_keys(['Name', 'Age', 'product_purchased', 'Amount_paid'])

In [87]:
# Using values() 

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.values()

dict_values(['Dhanush', 22, 'Laptop', 72000])

In [94]:
# Using update() 

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.update({"Amount_paid":81000})
print(customer_details)

{'Name': 'Dhanush', 'Age': 22, 'product_purchased': 'Laptop', 'Amount_paid': 81000}

In [96]:
# Using pop() 

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.pop("Name")
print(customer_details)

{'Age': 22, 'product_purchased': 'Laptop', 'Amount_paid': 72000}

In [97]:
# Using update() 

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.update({"Amount_paid":81000})
print(customer_details)

{'Name': 'Dhanush', 'Age': 22, 'product_purchased': 'Laptop', 'Amount_paid': 81000}

In [104]:
# Using popitem() - To remove last key value pairs

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.popitem()
print(customer_details)

{'Name': 'Dhanush', 'Age': 22, 'product_purchased': 'Laptop'}

In [108]:
# Using setdefault()

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.setdefault("city","vellore")
print(customer_details)

{'Name': 'Dhanush', 'Age': 22, 'product_purchased': 'Laptop', 'Amount_paid': 72000, 'city': 'vellore'}

In [109]:
# Using items()

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.items()
print(customer_details)

{'Name': 'Dhanush', 'Age': 22, 'product_purchased': 'Laptop', 'Amount_paid': 72000}

In [113]:
# Using get()

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
print(customer_details.get("Amount_paid"))

72000

In [114]:
# Using fromkeys() to set default values

fields = ["Name", "Age", "City", "Mobile"]
customer_form = dict.fromkeys(fields, "Pending")
print(customer_form)

{'Name': 'Pending', 'Age': 'Pending', 'City': 'Pending', 'Mobile': 'Pending'}

In [115]:
# Using copy()

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.copy()
print(customer_details)

{'Name': 'Dhanush', 'Age': 22, 'product_purchased': 'Laptop', 'Amount_paid': 72000}

In [116]:
# Using clear()

customer_details = {"Name":"Dhanush","Age":22,"product_purchased":"Laptop","Amount_paid":72000}
customer_details.clear()
print(customer_details)

{}

# Task_2. Create 3 DataFrames using Dictionaries

#### Example_1: Creating a students marks with respect to there names and subject

In [118]:
exam_marks = {"Name"   : ["Raju","Jaggu","Bheem","Kaliya","Dolu","Bolu"],
              "Maths"  : [63,72,96,63,95,99],
             "Science" : [99,72,52,99,99,100],
              "Social" : [61,73,92,100,98,96],
              "Tamil"  : [62,74,93,77,97,97],
              "English": [63,75,94,66,96,94],
              "P.E"    : [64,76,95,63,95,93]
             }

exam_marks

{'Name': ['Raju', 'Jaggu', 'Bheem', 'Kaliya', 'Dolu', 'Bolu'],
 'Maths': [63, 72, 96, 63, 95, 99],
 'Science': [99, 72, 52, 99, 99, 100],
 'Social': [61, 73, 92, 100, 98, 96],
 'Tamil': [62, 74, 93, 77, 97, 97],
 'English': [63, 75, 94, 66, 96, 94],
 'P.E': [64, 76, 95, 63, 95, 93]}

In [120]:
import pandas as pd
pd.DataFrame(data = exam_marks)

     Name  Maths  Science  Social  Tamil  English  P.E
0    Raju     63       99      61     62       63   64
1   Jaggu     72       72      73     74       75   76
2   Bheem     96       52      92     93       94   95
3  Kaliya     63       99     100     77       66   63
4    Dolu     95       99      98     97       96   95
5    Bolu     99      100      96     97       94   93

#### Example_2: Product Sales Details

In [126]:
product_sales_details = {"Products"          : ["Laptop","Mobiles","Tv","Ac","Fridge","Earphones"],
                         "Sold_out"          : [88,100,75,50,40,20],
                         "Offers_on_products": [20,30,50,10,20,5],
                          "Reminding_stocks" : [20,10,40,50,60,70]
                        }
product_sales_details

{'Products': ['Laptop', 'Mobiles', 'Tv', 'Ac', 'Fridge', 'Earphones'],
 'Sold_out': [88, 100, 75, 50, 40, 20],
 'Offers_on_products': [20, 30, 50, 10, 20, 5],
 'Reminding_stocks': [20, 10, 40, 50, 60, 70]}

In [127]:
import pandas as pd
pd.DataFrame(data = product_sales_details)

    Products  Sold_out  Offers_on_products  Reminding_stocks
0     Laptop        88                  20                20
1    Mobiles       100                  30                10
2         Tv        75                  50                40
3         Ac        50                  10                50
4     Fridge        40                  20                60
5  Earphones        20                   5                70

#### Example_3: Hospital Patient Records

In [130]:
Patient_records = {"Name"          : ["Raju","Nobita","Shinchan","Doraemon","Naruto","Luffy"],
                  "Blood_group"    : ["A+","A-","B+","AB-","O+","AB+"],
                  "Health_issues"  : ["Fever","Cold","Headache","Cough","Stomach Pain","Back Pain"],
                  "Admit_date"     : ["12-05-1991","23-08-1993","15-02-1995","07-11-1996","19-06-1998","28-09-1999"],
                  "Discharge_Date" : ["15-05-1991","25-08-1993","18-02-1995","10-11-1996","22-06-1998","30-09-1999"],
                  "Fees"           : [500, 300, 400, 350, 600, 450]}
Patient_records

{'Name': ['Raju', 'Nobita', 'Shinchan', 'Doraemon', 'Naruto', 'Luffy'],
 'Blood_group': ['A+', 'A-', 'B+', 'AB-', 'O+', 'AB+'],
 'Health_issues': ['Fever',
  'Cold',
  'Headache',
  'Cough',
  'Stomach Pain',
  'Back Pain'],
 'Admit_date': ['12-05-1991',
  '23-08-1993',
  '15-02-1995',
  '07-11-1996',
  '19-06-1998',
  '28-09-1999'],
 'Discharge_Date': ['15-05-1991',
  '25-08-1993',
  '18-02-1995',
  '10-11-1996',
  '22-06-1998',
  '30-09-1999'],
 'Fees': [500, 300, 400, 350, 600, 450]}

In [131]:
import pandas as pd
pd.DataFrame(data = Patient_records)

       Name Blood_group Health_issues  Admit_date Discharge_Date  Fees
0      Raju          A+         Fever  12-05-1991     15-05-1991   500
1    Nobita          A-          Cold  23-08-1993     25-08-1993   300
2  Shinchan          B+      Headache  15-02-1995     18-02-1995   400
3  Doraemon         AB-         Cough  07-11-1996     10-11-1996   350
4    Naruto          O+  Stomach Pain  19-06-1998     22-06-1998   600
5     Luffy         AB+     Back Pain  28-09-1999     30-09-1999   450