## 1. Perform initial analysis

* rows - Records/observation
* column - Features/Parameters

In [43]:
import pandas as pd

In [45]:
restaurent_details = pd.read_csv(filepath_or_buffer = "dataset.csv")
restaurent_details

,Restaurant_ID,Restaurant_Name,Cuisine,City,State,Rating,Delivery_Time_Min,Menu_Item,Category,Price,Calories,Is_Veg
0,R0185,BBQ Nation,American,Dallas,TX,5.0,28,Butter Chicken,Starter,$13.99,575,No
1,R0129,Pizza Palace,Italian,Chicago,IL,3.7,60,Taco,Main Course,$4.99,127,No
2,R0253,BBQ Nation,American,Los Angeles,CA,3.9,44,Taco,Dessert,$4.99,485,Yes
3,R0043,BBQ Nation,American,Chicago,IL,4.6,38,Sushi Roll,Dessert,$11.99,972,Yes
4,R0028,Dragon Wok,Chinese,Dallas,TX,3.7,56,Coffee,Dessert,$3.99,1179,No
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,R0201,Spice Route,Indian,Phoenix,AZ,4.1,40,Burger,Snack,$8.99,1139,Yes
1996,R0158,Healthy Bowl,Healthy,Boston,MA,4.4,17,Butter Chicken,Starter,$13.99,332,No
1997,R0266,Healthy Bowl,Healthy,Boston,MA,4.3,55,Pizza,Starter,$12.99,1005,Yes
1998,R0206,Healthy Bowl,Healthy,Los Angeles,CA,3.5,48,Salad,Dessert,$7.49,787,Yes
1999,R0253,Cafe Delight,Cafe,Los Angeles,CA,4.0,29,Butter Chicken,Main Course,$13.99,539,No

In [46]:
# Functions - ()
# Attributes - None

restaurent_details.shape

# We need to say like , the client provided 10 obervations with 8 parameters

(2000, 12)

In [47]:
# Chain of function - Using function in continues
# isnull()          - Checks any null values are present inside the dataset
# sum()             - It will gives sum of all null values inside the dataset

restaurent_details.isnull().sum()

Restaurant_ID        0
Restaurant_Name      0
Cuisine              0
City                 0
State                0
Rating               0
Delivery_Time_Min    0
Menu_Item            0
Category             0
Price                0
Calories             0
Is_Veg               0
dtype: int64

In [48]:
restaurent_details.dtypes

Restaurant_ID         object
Restaurant_Name       object
Cuisine               object
City                  object
State                 object
Rating               float64
Delivery_Time_Min      int64
Menu_Item             object
Category              object
Price                 object
Calories               int64
Is_Veg                object
dtype: object

In [49]:
# describe() - Satestical representation

restaurent_details.describe(include = 'all')

,Restaurant_ID,Restaurant_Name,Cuisine,City,State,Rating,Delivery_Time_Min,Menu_Item,Category,Price,Calories,Is_Veg
count,2000,2000,2000,2000,2000,2000.000000,2000.000000,2000,2000,2000,2000.000000,2000
unique,300,10,9,8,7,NaN,NaN,10,5,10,NaN,2
top,R0286,Healthy Bowl,American,Houston,TX,NaN,NaN,Salad,Starter,$7.49,NaN,No
freq,14,228,377,272,498,NaN,NaN,225,415,225,NaN,1022
mean,NaN,NaN,NaN,NaN,NaN,4.244800,37.886500,NaN,NaN,NaN,635.809500,NaN
std,NaN,NaN,NaN,NaN,NaN,0.429459,13.539841,NaN,NaN,NaN,319.611187,NaN
min,NaN,NaN,NaN,NaN,NaN,3.500000,15.000000,NaN,NaN,NaN,81.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,3.900000,26.000000,NaN,NaN,NaN,348.750000,NaN
50%,NaN,NaN,NaN,NaN,NaN,4.200000,38.000000,NaN,NaN,NaN,646.500000,NaN
75%,NaN,NaN,NaN,NaN,NaN,4.600000,50.000000,NaN,NaN,NaN,910.250000,NaN
max,NaN,NaN,NaN,NaN,NaN,5.000000,60.000000,NaN,NaN,NaN,1200.000000,NaN

### 1.1 Find out menu items.

In [50]:
# It gives the number of unique values of whole dataset

restaurent_details.nunique()

Restaurant_ID        300
Restaurant_Name       10
Cuisine                9
City                   8
State                  7
Rating                16
Delivery_Time_Min     46
Menu_Item             10
Category               5
Price                 10
Calories             933
Is_Veg                 2
dtype: int64

In [52]:
# I need only "Menu_Item" so iam using unique. Iam slicing parameters to pick one observation so that's why iam using [].

print(restaurent_details["Menu_Item"].unique())

['Butter Chicken' 'Taco' 'Sushi Roll' 'Coffee' 'Burger' 'Salad' 'Pizza'
 'Noodles' 'Pasta' 'Paneer Tikka']

### 1.2 Finding Top 5 selling items.

* Step_1 = Iam using groupby() to combinie two obervations as a output (items,Rating).
* Step_2 = Iam using sum() to see the items.
* step_3 = Using sort_value() will makes the dataset in asending order.
* step_4 = To see top 5 salary i need to reverse it so i make the ascendinig = False.
* step_5 = To visualize top 5 i used head()

In [55]:
# Used chain methods

restaurent_details.groupby(by = "Menu_Item")["Rating"].sum().sort_values(ascending = False).head()

Menu_Item
Salad             945.3
Pasta             942.1
Sushi Roll        902.9
Pizza             892.5
Butter Chicken    883.9
Name: Rating, dtype: float64

### 1.2 Finding Least 5 salary brought by the employees

In [56]:
# Used chain methods

restaurent_details.groupby(by = "Menu_Item")["Rating"].sum().sort_values().head()

Menu_Item
Paneer Tikka    717.3
Noodles         751.6
Taco            762.9
Burger          826.0
Coffee          865.1
Name: Rating, dtype: float64

## Data Cleaning

In [58]:
# I need to change the price data (object) into numbers

restaurent_details

,Restaurant_ID,Restaurant_Name,Cuisine,City,State,Rating,Delivery_Time_Min,Menu_Item,Category,Price,Calories,Is_Veg
0,R0185,BBQ Nation,American,Dallas,TX,5.0,28,Butter Chicken,Starter,$13.99,575,No
1,R0129,Pizza Palace,Italian,Chicago,IL,3.7,60,Taco,Main Course,$4.99,127,No
2,R0253,BBQ Nation,American,Los Angeles,CA,3.9,44,Taco,Dessert,$4.99,485,Yes
3,R0043,BBQ Nation,American,Chicago,IL,4.6,38,Sushi Roll,Dessert,$11.99,972,Yes
4,R0028,Dragon Wok,Chinese,Dallas,TX,3.7,56,Coffee,Dessert,$3.99,1179,No
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,R0201,Spice Route,Indian,Phoenix,AZ,4.1,40,Burger,Snack,$8.99,1139,Yes
1996,R0158,Healthy Bowl,Healthy,Boston,MA,4.4,17,Butter Chicken,Starter,$13.99,332,No
1997,R0266,Healthy Bowl,Healthy,Boston,MA,4.3,55,Pizza,Starter,$12.99,1005,Yes
1998,R0206,Healthy Bowl,Healthy,Los Angeles,CA,3.5,48,Salad,Dessert,$7.49,787,Yes
1999,R0253,Cafe Delight,Cafe,Los Angeles,CA,4.0,29,Butter Chicken,Main Course,$13.99,539,No

In [60]:
restaurent_details["Price"].str.replace("$","")

0       13.99
1        4.99
2        4.99
3       11.99
4        3.99
        ...
1995     8.99
1996    13.99
1997    12.99
1998     7.49
1999    13.99
Name: Price, Length: 2000, dtype: object

In [61]:
# changing the object into float

restaurent_details["Price"].str.replace("$","").astype(float)

0       13.99
1        4.99
2        4.99
3       11.99
4        3.99
        ...
1995     8.99
1996    13.99
1997    12.99
1998     7.49
1999    13.99
Name: Price, Length: 2000, dtype: float64

In [70]:
# To store in dataset 

restaurent_details

,Restaurant_ID,Restaurant_Name,Cuisine,City,State,Rating,Delivery_Time_Min,Menu_Item,Category,Price,Calories,Is_Veg
0,R0185,BBQ Nation,American,Dallas,TX,5.0,28,Butter Chicken,Starter,13.99,575,No
1,R0129,Pizza Palace,Italian,Chicago,IL,3.7,60,Taco,Main Course,4.99,127,No
2,R0253,BBQ Nation,American,Los Angeles,CA,3.9,44,Taco,Dessert,4.99,485,Yes
3,R0043,BBQ Nation,American,Chicago,IL,4.6,38,Sushi Roll,Dessert,11.99,972,Yes
4,R0028,Dragon Wok,Chinese,Dallas,TX,3.7,56,Coffee,Dessert,3.99,1179,No
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,R0201,Spice Route,Indian,Phoenix,AZ,4.1,40,Burger,Snack,8.99,1139,Yes
1996,R0158,Healthy Bowl,Healthy,Boston,MA,4.4,17,Butter Chicken,Starter,13.99,332,No
1997,R0266,Healthy Bowl,Healthy,Boston,MA,4.3,55,Pizza,Starter,12.99,1005,Yes
1998,R0206,Healthy Bowl,Healthy,Los Angeles,CA,3.5,48,Salad,Dessert,7.49,787,Yes
1999,R0253,Cafe Delight,Cafe,Los Angeles,CA,4.0,29,Butter Chicken,Main Course,13.99,539,No

In [71]:
restaurent_details.dtypes

Restaurant_ID         object
Restaurant_Name       object
Cuisine               object
City                  object
State                 object
Rating               float64
Delivery_Time_Min      int64
Menu_Item             object
Category              object
Price                float64
Calories               int64
Is_Veg                object
dtype: object

In [72]:
restaurent_details.describe()

            Rating  Delivery_Time_Min        Price     Calories
count  2000.000000        2000.000000  2000.000000  2000.000000
mean      4.244800          37.886500     9.590500   635.809500
std       0.429459          13.539841     3.116449   319.611187
min       3.500000          15.000000     3.990000    81.000000
25%       3.900000          26.000000     7.490000   348.750000
50%       4.200000          38.000000    10.490000   646.500000
75%       4.600000          50.000000    11.990000   910.250000
max       5.000000          60.000000    13.990000  1200.000000

### 3. Pandas Data Structure
- 1D - series
- 2D - DataFrame

In [4]:
# 1D - Series

import pandas as pd

pd.Series(data = [1,2,3.5,"$4.6"])

0       1
1       2
2     3.5
3    $4.6
dtype: object

In [5]:
# 2D - DataFrame

pd.DataFrame(data = [1,2,3.5,"$4.6"])

      0
0     1
1     2
2   3.5
3  $4.6

## 4. Filtering & Selection & Sorting

In [6]:
euro_footbal = pd.read_csv("Euro_2012.csv")
euro_footbal

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [7]:
# Display all obervations

pd.set_option("display.max_column",None)

In [8]:
euro_footbal.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19

### Filtering

In [9]:
# Iam going to filter important observations.
# If the observations are more than one , then use [].
# For slicing some observations from the datasets use [].

filtered_euro = euro_footbal[["Team","Goals","Yellow Cards","Red Cards"]]

In [10]:
filtered_euro.head()

             Team  Goals  Yellow Cards  Red Cards
0         Croatia      4             9          0
1  Czech Republic      4             7          0
2         Denmark      4             4          0
3         England      5             5          0
4          France      3             6          0

##  Sorting
### Top 5 Team to conceed more yellow card

In [11]:
filtered_euro.sort_values(by = "Yellow Cards",ascending = False).head(6)

              Team  Goals  Yellow Cards  Red Cards
7            Italy      6            16          0
10        Portugal      6            12          0
13           Spain     12            11          0
0          Croatia      4             9          0
6           Greece      5             9          1
1   Czech Republic      4             7          0

### Top 5 Team to conceed more Red card

In [12]:
filtered_euro.sort_values("Red Cards",ascending = False).head()

                   Team  Goals  Yellow Cards  Red Cards
6                Greece      5             9          1
9                Poland      2             7          1
11  Republic of Ireland      1             6          1
0               Croatia      4             9          0
1        Czech Republic      4             7          0

### List the Team which as more than 8 Yellow cards

In [13]:
filtered_euro[filtered_euro["Yellow Cards"] >= 8]

        Team  Goals  Yellow Cards  Red Cards
0    Croatia      4             9          0
6     Greece      5             9          1
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0

# 4. How to deal with Missing Values

## Level - 1 of Data Cleaning

In [14]:
employee_data = pd.read_csv("emp_data.csv")
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

### Step 1 - Remove Duplicate data

In [15]:
employee_data.shape

(8, 5)

In [16]:
employee_data.drop_duplicates(inplace = True)

# To save this updated data into current data, i will use inplace = True

In [17]:
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

### Step 2 - Find null values

In [18]:
employee_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

### Step 3 - Founded three null values, Going to drop it.

In [19]:
employee_data.dropna(inplace = True)

In [20]:
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [21]:
employee_data.shape

(4, 5)

### Step 4 - Documentation

* Removed 1 duplicate data
* Removed 3 null data
* Observation and Perameters are Before (8,5)
* Observation and Perameters are Now (4,5)
* Sending this updated file to client for approval, If client approved then, proceed with model buil

## Level - 2 of Data Cleaning

* readcsv - It will read only one csv sheet.
* readexcel - It will access multiple sheets which inside one dataset. Using sheet names.

In [22]:
# So if you are having csv file but u need to access different sheets, Then you need to change the csv file into excel file.
# And then access it with sheet name.

In [23]:
import pandas as pd

In [25]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
new_employee = pd.read_excel("emp_data_excel.xlsx",sheet_name ="More_employee_data")
new_employee

            Name   Age Department   Salary  Join_Date
0         Rajesh  29.0        Ops  60000.0 2023-05-21
1          Nasir  31.0    IT Tech  62000.0 2020-11-12
2         Mathew   NaN    Support  50000.0 2025-01-15
3        Gilbert  29.0        Ops  60000.0 2021-05-21
4          Kevin  28.0    Support  61000.0 2024-07-30
5          Navin  35.0    Support  72000.0 2023-08-19
6            NaN  40.0    IT Tech  64000.0 2022-09-10
7         Roshan  31.0    IT Tech      NaN 2020-11-12
8      Kuppusamy  28.0        Ops      NaN 2021-05-21
9          Ajesh  28.0    Support      NaN 2024-07-30
10          Diya  31.0    IT Tech  63000.0 2020-11-12
11        Mathew   NaN    Support  50000.0 2025-01-15
12  Jagadheswari  28.0    IT Tech      NaN        NaT
13          Mani  28.0        Ops      NaN 2021-05-21

#### Follow same steps to clean data

In [42]:
# Remove duplicate

new_employee.drop_duplicates(inplace = True)
new_employee

            Name   Age Department   Salary  Join_Date
0         Rajesh  29.0        Ops  60000.0 2023-05-21
1          Nasir  31.0    IT Tech  62000.0 2020-11-12
2         Mathew   NaN    Support  50000.0 2025-01-15
3        Gilbert  29.0        Ops  60000.0 2021-05-21
4          Kevin  28.0    Support  61000.0 2024-07-30
5          Navin  35.0    Support  72000.0 2023-08-19
6            NaN  40.0    IT Tech  64000.0 2022-09-10
7         Roshan  31.0    IT Tech      NaN 2020-11-12
8      Kuppusamy  28.0        Ops      NaN 2021-05-21
9          Ajesh  28.0    Support      NaN 2024-07-30
10          Diya  31.0    IT Tech  63000.0 2020-11-12
12  Jagadheswari  28.0    IT Tech      NaN        NaT
13          Mani  28.0        Ops      NaN 2021-05-21

In [44]:
# Find and remove null values

new_employee.isna().sum()

Name          1
Age           1
Department    0
Salary        5
Join_Date     1
dtype: int64

## Try to find patten and impute data before dropping it.
* Finding exact place of null values.

In [55]:
new_employee[new_employee["Department"] == "Support"]

     Name   Age Department   Salary  Join_Date
2  Mathew   NaN    Support  50000.0 2025-01-15
4   Kevin  28.0    Support  61000.0 2024-07-30
5   Navin  35.0    Support  72000.0 2023-08-19
9   Ajesh  28.0    Support      NaN 2024-07-30

In [54]:
new_employee[ (new_employee["Department"] == "Support") & (new_employee["Salary"].isna()) ]

    Name   Age Department  Salary  Join_Date
9  Ajesh  28.0    Support     NaN 2024-07-30

In [56]:
new_employee[new_employee["Department"] == "IT Tech"]

            Name   Age Department   Salary  Join_Date
1          Nasir  31.0    IT Tech  62000.0 2020-11-12
6            NaN  40.0    IT Tech  64000.0 2022-09-10
7         Roshan  31.0    IT Tech      NaN 2020-11-12
10          Diya  31.0    IT Tech  63000.0 2020-11-12
12  Jagadheswari  28.0    IT Tech      NaN        NaT

In [57]:
new_employee[ (new_employee["Department"] == "IT Tech") & (new_employee["Salary"].isna()) ]

            Name   Age Department  Salary  Join_Date
7         Roshan  31.0    IT Tech     NaN 2020-11-12
12  Jagadheswari  28.0    IT Tech     NaN        NaT

In [59]:
new_employee[ (new_employee["Department"] == "Ops") & (new_employee["Salary"].isna()) ]

         Name   Age Department  Salary  Join_Date
8   Kuppusamy  28.0        Ops     NaN 2021-05-21
13       Mani  28.0        Ops     NaN 2021-05-21

In [60]:
new_employee[ (new_employee["Department"] == "Support") & (new_employee["Age"].isna()) ]

     Name  Age Department   Salary  Join_Date
2  Mathew  NaN    Support  50000.0 2025-01-15